doctrine:
    dbal:
        default_connection: employee
        connections:
            employee:
                url: '%env(resolve:DATABASE_URL_EMPLOYEE)%'
            product:
                url: '%env(resolve:DATABASE_URL_PRODUCT)%'
            rental:
                url: '%env(resolve:DATABASE_URL_RENTAL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'