employee_v1_controllers:
  resource: ../Employee/config/routes/routes.yaml
  prefix: 'employee/v1/'



#health_check:
#  path: /health-check
  # the controller value has the format 'controller_class::method_name'
#  controller: '@Employee\Controller\HealthCheckController'

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
